### ISSUE TITLE
After running bash download_data.sh, I am getting empty files. Is it supposed to be that way?

### ISSUE THREAD

**Issue by Aman2493** [facebookresearch/hypernymysuite#6]

**Comment by stephenroller** [comment]
No, that's weird. Can you elaborate? Which files are empty?

What OS are you using? Can you provide a log of running `download_data.sh`?

**Comment by Aman2493** [comment]
I am using Windows 10. When I run bash download_data.sh, it only downloads the bless.tsv file and exits without any error. Also, this file is empty.

**Comment by stephenroller** [comment]
I haven’t a clue how to develop for Windows.

I recommend using a Ubuntu VM or similar. If you can port the download script so that it works in Windows and Linux I would accept the patch. As is, I don’t have much expectation for it to work.

I would’ve liked to have distributed the raw files but there were copyright concerns. Sorry.
